sudo: false
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- echo "This design module has no tests"
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: B8FSjTVqpbg+kkaZD0NuzjDeEC2i1pz1oFHryUcmiBdmI/lxQgxx9d0zzZ7aOqtcF5IW3uESFOvDfpdbxm4EDRZnlkQS2wXEfvpYjeWv2EqDLeKl/oeUHEdowajgxrXK7+6M3hfm8sZwPh6+L1w8hfmpYkN+GWHQNltML0JuPXan7XxAdGfRG76L3bjauBLSmvNBvlLFtZW+II3b527gjj6dar8cNliEtH5hp9gTufEElPTkQOge7nCbIAdZRxKkAOuIaqGYgDvW0Xe0W37N5wrF2E1iQDed1eDLiiRwDbItKO35L6gEPrzr86KqTTdmXnVwyjsj6OovEG3AwZjSoXmAUVMXQC71FZgVtLRf8aO1Llmtb95mV2UmnVgWcicMmYamQ4MJtven6tcr6PvuFiKhmtQViuDbHSub2MPcoE49XgA83udJ+JRk2Jfa7oH6BWjLjrXtw8VGBrzqkJP8mDq2CTJk2SVAurFf96O7YYPOB8USh+7PyVy9w/sJ6+4syLdtGr8fjRRwV5eRmcIop7cyuyHxnSBCnSz9gZw+zWqY6rk0plGFIv7GiMKrJ2Vx5MS/ZlZgtmgjQXnnlUKRpivgstFpOuLHuI40iD2QQzWoHa1j+VKwiR21mNq6nF5nSFcHOejiJMr2Piy1aANrwbUvZAtbSGeeQAiGXHK+UZA=
  - secure: biBYk9blGDqXdGXGPX0CqkQFCYd/l2gFVtwnBqlvETmqhJUwYIKrK/Amb1g4lvfpia2akRRzVodF0m6bvGvdbVUYl+Jwj3DUl0qipKQS0skLondhBiVqd4j+FZkEpg8/JNE5UzmmVvHfzAOLV5a6ZTdbi2XHsJj05dvnjQ9DJsffQO4VMyfgfJ2HNgCFDPPFTika3OzCALVJ2gy8niEF2t866LU8ab+XNjMwKtZAVKxpbmKj7z+Hx+/goYHkR5Dhj08XpxNGysH2t35d8wVMidTksmmLpO8bCamM2qx2GctT5eeZI3uwH7c1IRLRuNV0y2IwWHyT3A8KMa9FKsQ6+007daSKomNIuWgC+LiYC8P0DCr2fEbVjoVgOgXgpcbM7FfA3FiQ9IEIl7tiX5Mb2KJHz0s0+09jkFvoornKMYGxtuW93idJBKU6Hh4xmd2thpCcM+VLL6WxNhaq35DJtxUBPQ1nRlMWcFj4zEoG6F53FCtsJvc1+qnwYqGVO1gP9TXPG+Exn30ij18bBHoE+U1U+qy9u1d68sSTazs5QBRaR+gSKW9H+iTvG+ABYtcwBvF7U7Tk53yHdYIIITwgsGFEiTyMha0wOCTNuKSlc23O22XKLy2szyMYXjCcdnlRcjYM59iqlgtTahm6ibHxqIo+riOIgdvwok94esCoqqY=
  - secure: DdCA908EGjdrRj1J5Yr7/vDr2vmA9rMCqWIr+6Xwq9WugvjDzyWsWXhvu93ghGV+IRGdY7H+HLcz8OxBaUqYrbUBQABZiE7Ru18GxCQJhMvmWnTiYOzsRG5I3Uc/6acxXgaUO+JYp+DGBvYpQ16hLxNSjeeOg85L4eoulIY4QSXL0pgtS9U78XNN51+2nzPpHqCNqngl+u8fPADKgvBeCM3vKiyHct39X5PE0P4Q/kicEmu4PAw+tF9sWT8Q0TGVEUgA9DTC1WQScgQXxxajNdeADxSZwgZ4/PVaHhAFGK5QK7aU2VFXBBD9GWcQriLasgXtDsGxtZ5xG2gKNBsftOFAbsgBybp04opyI8U2oIFSNnrNkd5xYKi132OEjYlIwHT+Oq/u+VDYAKCqTBdk1oKD45FvkzfAw4WjaOf7YNPSrJ+e4Rb4a4Qwk7IZKWCz+Muqgy/yZbhVN2xdz2RsM4IN17Eyfv3fW69SgiBBaYFOOWUtZFtj9meb1flKMA4MoaMZKSNe+OfD8qTf3ntlNWXAXQwpcLyLmA80X8FqX6PhBS+mxKynnM/95Ckihx5EXlzlYidMjregIYaStr9ZZ78LnQPOh9qJtxKv7bP+q1Z+4fRSRI4X2oa4jpDbBc6ABkdksrc6Amm3zdQw4GjTBsIFekpjyEMkRy6kXYDdRfo=
  - secure: jMpCt33zxfIa0ov4Pe2jnZZHjH33hcF+CSY3bEJiqE1+kaXbOuP07vcj7NO2ssLWhmfpNULooXwN9rCHc/xKUydkO9s9Mit9e0J3I979c7eB5fa5FBFUnFaYH/NJKlAFJ37jlEgXqwA7XCJ4Qh+urUntY1tbxcRg+D6JKI7dru/Yv7LVnvLDZwFKInIypQ0o1P0BAxTpzCYF/gg2j2ZJhqSJLITyheONrx3MYYPcKpq4lpGzitN8Vo/dkJtToLtFVvN5bb3KYAe6JX3aX3CFUcY6cYYjB+z6Bfg5Nwuh5W3zbnFM8r36fXlLYuh8dn+5gHeoCAuI+DXRsOeD4+peMZiPMf5H1u0jQrStWvIyoKLo2yYT8eW6si2B+v6jbXFCSQgb26Vb5u2I8WpqB1g2DJw4L9xUNUjg2bjD6lgf360ma7+ONUlVpqgSiBHJjwfwgc7EmN1USEHN/2VJwIWN9f10j+B8Abv5PQM+IAFWkSaGekGf2qgQq4AxVUBgYpR8ZkNRD5KfBSdN6RGadsAp8Rx68nf0x7ugLXVZT9UBS/kprY5j61DUJsI4IOUygQkYQhye6rjMR2JSqXei30ku3P4jTJ1tY5gSc7WlmJ2NXfUj31sSFdlV+tDxkU1DA/WbK0foQx0KRAIqH+Md8nJD1o6lLyQhogJogurqh1sGV1g=
